### ISSUE TITLE
Github Workflows Not Running

### ISSUE THREAD

**Issue by FroggyPanda** [FroggyPanda/better-supabase-types#12]
I tried to set up GitHub workflows to make sure people's pull requests can compile and pass test cases and lints, but it seems that the workflows only run when the PR is made by me (the owner of this repo).  Would anyone happen to know how to fix this issue?  I also followed [this video](https://www.youtube.com/watch?v=eh89VE3Mk5g&t=2s) to make my Github workflow.

[PR made by me that has a GitHub workflow run](https://github.com/FroggyPanda/better-supabase-types/pull/10/checks)
[PR made by someone else that did not have a GitHub workflow run](https://github.com/FroggyPanda/better-supabase-types/pull/9/checks)

**Comment by cpannwitz** [comment]
I'd assume it's because the PR is coming from another repo - the fork where the PR originates.
I guess this doesn't trigger the workflow. But it's just an assumption.
