### ISSUE TITLE
Enums with special characters lead to error

### ISSUE THREAD

**Issue by cpannwitz** [FroggyPanda/better-supabase-types#14]
Hey, thanks for this lib and your work!

I've stumbled upon an error that is thrown by Typescript, if an Enum contains special characters in its name.
In our case those characters are dots (eg. `"my.permission.path"`).

The error thrown is this: `SyntaxError: An enum member name must be followed by a ',', '=', or '}'.`

I guess this could be handled [here](https://github.com/FroggyPanda/better-supabase-types/blob/6f2cee17b8b35ab9f96c408c70bd0f2aa989c254/src/utils/getEnumsProperties.ts#L53), I can submit a PR for this but I'd like to discuss the possible options - possibly handling other characters too - first :)

My expectation would be, at least in our case for eg. `"my.permission.path"`, that the Enum name would be converted to `mypermissionpath` or even better to `myPermissionPath`.

**Comment by barrymichaeldoyle** [comment]
I like the idea of a conversion to `myPermissionPath`

**Comment by FroggyPanda** [comment]
`myPermissionPath` seems like a good conversion to have.  And feel free to make a PR!

**Comment by cpannwitz** [comment]
Would be great to get the PR reviewed and merged :)
https://github.com/FroggyPanda/better-supabase-types/pull/15

**Comment by cpannwitz** [comment]
@FroggyPanda It seems, even though the package was published under `2.4.0` on NPM, the content is still the same as `2.3.0`.
Also it appears to be compiled differently than `2.3.0`, do you have any insights?

**Comment by FroggyPanda** [comment]
Yep thats all my bad, still trying to figure out how NPM publishing works lol.  I will publish it under `2.4.1` with the package actually built lol. And I added [tsup](https://www.npmjs.com/package/tsup) to handle the building and using tsc to lint the code.

**Comment by cpannwitz** [comment]
No problem, thanks for your work! I like the addition of tsup.
