### ISSUE TITLE
Singularized function names lead to duplicate identifiers

### ISSUE THREAD

**Issue by cpannwitz** [FroggyPanda/better-supabase-types#19]
Hey,

since the last update including the database function type generation we encountered some problems regarding duplicate identifiers of those function types.

The singularization (see here: https://github.com/FroggyPanda/better-supabase-types/blob/61c899d708b71cded764eea6e6a4953d86129fe4/src/generate.ts#L71C39-L71C39) is desirable for most of the entities, tables, enums, functions, ... but can lead to duplicates.

Example:
```
export type ArgsDetachTablespace = Database['public']['Functions']['detach_tablespace']['Args'];
export type ArgsDetachTablespace = Database['public']['Functions']['detach_tablespaces']['Args'];
```

Renaming them isn't an immediate option, since there are a lot of them.

What would be a good strategy to have singularized entity names, but an escape for those duplicates?

**Comment by barrymichaeldoyle** [comment]
This is a good question that we might need to think around for a bit.

A quick fix for now would be to turn off the `singular` flag, I think it is false by default thought so I'm not sure why the update is causing this issue for you 😕 

https://github.com/FroggyPanda/better-supabase-types#creating-singular-model-type-names-from-plural-table-names

**Comment by cpannwitz** [comment]
Oh wow, totally missed that I was generating with the `-s` singular flag!
But without it's leading to even bigger problems due to usage of the singularized types, which would need additional conversion, basically the same situation without this great lib.

For now I'm manually adapting the colliding types, seems like the smaller issue.

**Comment by barrymichaeldoyle** [comment]
All good, If you can produce a small example of what you get out in your
configuration vs what you want we could probably do something to sort it
out. I’m personally quite bogged down with work but there are some others
here who might pick it up :)

**Comment by FroggyPanda** [comment]
@cpannwitz in the example, you're showing two different function types, one with an S and one without.  Is that how it is in supabase, or did better-supabase-types do that?

And if you could provide us with an example schema and the commands you used to get the same output you are getting, that would be amazing.

**Comment by cpannwitz** [comment]
Sure! The snippet of the first post was the result of `better-supabase-types`.

The following is an extract of our current schema, generated by `supabase gen types typescript --local --schema public > schema.ts`:
```
export interface Database {
  public: {
    Functions: {
      detach_tablespace: {
        Args: {
          tablespace: unknown
          hypertable?: unknown
          if_attached?: boolean
        }
        Returns: number
      }
      detach_tablespaces: {
        Args: {
          hypertable: unknown
        }
        Returns: number
      }
    }
  }
}
```

The following is an extract of the result using `better-supabase-types` via the command `better-supabase-types -s -f -p .prettierrc.cjs -i schema.ts`:
```
// includes the same snippet as above

//Functions
export type ArgsDetachTablespace = Database['public']['Functions']['detach_tablespace']['Args'];
export type ReturnTypeDetachTablespace = Database['public']['Functions']['detach_tablespace']['Returns'];

export type ArgsDetachTablespaces = Database['public']['Functions']['detach_tablespaces']['Args'];
export type ReturnTypeDetachTablespaces = Database['public']['Functions']['detach_tablespaces']['Returns'];
```

As previously pointed out, I'm using the `-s` singularize flag, which is working correctly and is desired for 99% of all cases.
In this specific case we have two database functions which are originally named `detach_tablespace` and `detach_tablespaces` - one singular, one plural.

**Comment by FroggyPanda** [comment]
Interesting, it looks like I am not able to replicate that.  Here is a [StackBlitz project](https://stackblitz.com/edit/stackblitz-starters-n3h5dk), and you can run the command by going into the terminal and running:
```bash
npm run bst
```
Do make sure that you are using the current version `2.6.0`

**Comment by FroggyPanda** [comment]
@cpannwitz have you been able to figure it out?

**Comment by cpannwitz** [comment]
Hey, sorry for my absence, lots of stuff to do.
Currently the problem persists for us, but I assume it's our own problem, since we have double named functions (singular + plural). I fix the two occasions on our side by hand for now.
