### ISSUE TITLE
Export enums as types rather than enums

### ISSUE THREAD

**Issue by timlgl** [FroggyPanda/better-supabase-types#22]
Hi, 

currently, Database enums are exported as typescript enums. As I tend to work with types and prefer doing, I would appreciate the option to pass a flag, so that types are exported.

If I know you would include the feature in this repository, I'd be happy to create the PR for it!

**Comment by FroggyPanda** [comment]
@timlgl sorry for getting to this so late.  Here is a PR for this feature request.  Please take a look at it and let me know if you are expecting something else.

**Comment by timlgl** [comment]
@FroggyPanda awesome, thank you. One suggestion, but not really important:
You could also define the types likes this:
`export type SomeType = Database['public']['Enums']['some_type']`

Other than that, I am looking forward to using it! :)
