### ISSUE TITLE
Bumping prettier to v3 was a breaking change

### ISSUE THREAD

**Issue by dawnmist** [FroggyPanda/better-supabase-types#26]
FYI: Version 3 of prettier changes how it handles plugins, resulting in plugins that were written for prettier v2 needing to be upgraded to allow importing commonjs modules with ESM in order for them to work with prettier v3.

As a result, any project using one of these plugins that will have its build broken by the `better-supabase-types` patch version bump that upgraded prettier to v3.

~~I'm working around this at the moment by locking `better-supabase-types` to version 2.6.1 (last version to use prettier 2.x) until my required prettier plugins have all been upgraded to work with prettier 3~~ Edit: I've now checked my various plugins and they've now all released updates which they hadn't last time I'd checked, but I also felt it important to let you know that you've introduced a breaking change as a patch update (under semver rules it should have been a major update - i.e. moved better-supabase-types to 3.0.0 instead of 2.6.2).

**Comment by FroggyPanda** [comment]
Thats not good, im not sure if there is a way to change the npm version from `2.6.2` to `3.0.0` but if anyone does find a way to do that, or a clean way to push out a `3.0.0` update ill be more than happy to do this.
