### ISSUE TITLE
TODO Discussion: Have it possible to either make a new file or overwrite the input file

### ISSUE THREAD

**Issue by barrymichaeldoyle** [FroggyPanda/better-supabase-types#3]
Is it not currently possible to just make the `input` and `output` paths the same and therefor have the "new file" overwrite the input file? 

If this work's we could just update the README to instruct a user to do this to overwrite the input file like this:

```
npx better-supabase-types -i ./src/schema.ts -o ./src/schema.ts
```

**Comment by FroggyPanda** [comment]
(Im pretty sure you made this before you saw the addition with the force parameter a4c2533)
This totally is but I would ideally like it to just be `npx better-supabase-types -i ./src/schema.ts -f`

**Comment by barrymichaeldoyle** [comment]
Haha yep, I made this issue before you made that addition :) I've even updated the README to cater for it :) Glad it's resolved :)
