### ISSUE TITLE
Empty enum created when only has one value

### ISSUE THREAD

**Issue by 0x62** [FroggyPanda/better-supabase-types#37]
```
CREATE TYPE example AS ENUM (
  'example_value'
);
```

Creates an output of

```
export enum Example {}
```

The expected output is (assuming pascal case settings)

```
export enum Example {
   'ExampleValue' = 'example_value'
}
```

**Comment by FroggyPanda** [comment]
Found the [source of the issue](https://github.com/FroggyPanda/better-supabase-types/blob/59457f7d9665b3a25500b8f76295d90fb22ff66d/src/utils/getEnumsProperties.ts#L74) but currently having trouble to find a fix for it.  The [linked](https://github.com/FroggyPanda/better-supabase-types/blob/59457f7d9665b3a25500b8f76295d90fb22ff66d/src/utils/getEnumsProperties.ts#L74) variable does not have anything in its array when there is an enum with one property.

I have tried changing `.getChildrenOfKind(ts.SyntaxKind.UnionType)` to `.getChildren()` but that does not seem to fix the issue.

Just putting this information out there if anyone else is able to use this as a stepping point and is able to find a fix.
