### ISSUE TITLE
Issue in line endings

### ISSUE THREAD

**Issue by BboyKeen** [FroggyPanda/better-supabase-types#39]
Hey,
Thanks for this useful package.
It looks like line endings are broken in 2.7.5 for MacOs and Linux users as per the following error I get when using it.

`env: node\r: No such file or directory`

All files are using CRLF instead of LF. I think the previous version didn't have this issue.

See here for reference : https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo

**Comment by FroggyPanda** [comment]
Unfortunately, I don't own something that runs MacOS and don't have a Linux system installed, so I can't test any changes I make.
Odd how this is now an issue since the `.prettierrc` has `"endOfLine": "lf",` which shouldn't make this an issue.

**Comment by BboyKeen** [comment]
Yes, kinda weird if nothing changed on your side..
Maybe something related to your git configuration.

There is some ideas here : https://stackoverflow.com/questions/72578467/prettier-write-replaces-lf-by-crlf-on-windows

Btw, I forked your project to push a PR but files were already in LF when I cloned the project. 

It may be related to the built package you published to NPM.

**Comment by FroggyPanda** [comment]
> It may be related to the built package you published to NPM.

That is a possibility.  Before, this package was using [tsup](https://github.com/egoist/tsup) to build the versions.  However, I disliked the build step when making changes, so I removed it.  But, as you said, the files are already in LF, so it is really strange that there are issues now.

If you could, try converting all of the files with this command `dos2unix` and see if you are able to use the package.
[https://stackoverflow.com/questions/3569997/how-to-find-out-line-endings-in-a-text-file](https://stackoverflow.com/questions/3569997/how-to-find-out-line-endings-in-a-text-file)

**Comment by BboyKeen** [comment]
It may be the culprit yes.. 

I did exactly that in the node_modules/better-supabase-types folder and all was working fine after.

**Comment by FroggyPanda** [comment]
Go ahead and see if you are able use the package this linked pr #40.

**Comment by BboyKeen** [comment]
Thanks, I will test it in few hours.

However maybe it could be less intrusive in your workflow to use something on Git directly. 

See https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/

**Comment by BboyKeen** [comment]
I checked out the PR using yarn with `yarn add FroggyPanda/better-supabase-types#40/head`.
Files are in LF as they were when I cloned the project so no surprise. I think there is some kind of git magic performed by my git config.

I downloaded the 2.7.0 I was using before with `npm pack better-supabase-types@2.7.0` and the 2.7.5 to compare both versions.
It looks like you changed your way of building the project. Before, I guess using tsup generated a file in the dist folder with LF line endings by default

Now that you stopped using tsup, I imagine you push your source files directly as an NPM package and that's why CRLF are preserved in your distributed NPM package.

**Comment by Magellol** [comment]
For anyone else looking for a simple workaround for unix systems, I've added a `postinstall` script that runs `prettier` on this package's node modules.

`package.json`
```json
{
  "scripts": {
    "postinstall": "prettier --with-node-modules --write ./node_modules/better-supabase-types/**/*.js"
  }
}
```
