### ISSUE TITLE
New Feature: Export Insert and Update types

### ISSUE THREAD

**Issue by TimurKr** [FroggyPanda/better-supabase-types#8]
Idea for a new feature:

Export the `Insert` and `Update` classes at the end of the file as well. This seems like a pretty simple feature to add, and it would remove the need for complicated imports when dealing with forms. 

My suggestion would be to export types related to a table named `todo` like this: 

```
export type Todo = Database['public']['Tables']['todo']['Row'];
export type InsertTodo = Database['public']['Tables']['todo']['Insert'];
export type UpdateTodo = Database['public']['Tables']['todo']['Update'];
```

This would allow for:

```
import type { InsertTodo } from 'database.ts'

type InsertTodos = InsertTodo[]; // In case of doing bulk insert
```

**Comment by barrymichaeldoyle** [comment]
I agree, this is a decent add, did a similar think in my library :)

**Comment by FroggyPanda** [comment]
Accepted PR #9 👍
